### ISSUE TITLE
設定ツールでA.I.Voiceのruleを生成するとかんしくん側でエラーが起きる。

### ISSUE THREAD

**Issue by maki-07061210** [oov/forcepser#18]
原因はわかってるんですが
A.I.VOICEのときだけfile変数になるはずの変数がfilereになり。
また、^.+?などのよくわからない文字列がfile変数に格納されます
例: filere = '''^.+?_足立 レイ(?:| - .+?)_.*?\.[Ww][Aa][Vv]$'''

filereをfileにし
'''*_$CharName_*.wav'''
($CharNameは任意のキャラクター名)
となるようにしていただければありがたいです

私の知り合い何人かが犠牲者になっています

**Comment by maki-07061210** [comment]
3行目のfile変数はfilere変数の間違いです

**Comment by oov** [comment]
`filere` は v1.4 以降で使える機能であり、そこでトラブルが起こるということは
バージョンが適切ではない状態で使おうとしてハマった、ということでしょうか。

何らかの理由で issue を閉じるに至ったのであれば、その理由も添えてもらえると嬉しいです。
